### PR TITLE
The Web Notification API

### PR DESCRIPTION
**Pull request by hinablue**
There is the Web Notification API with Famo.us.

Reference:
[MDN, Notification - Web API]([https://developer.mozilla.org/en-US/docs/Web/API/notification)

### CODE REVIEW

**Comment by dmvaldman** [comment]
Thanks for the request! I suppose my main issue is, do you think having a Famo.us module that wraps the Web Notification API benefits the end user, or could they just use the native implementation?

**Comment by hinablue** [comment]
I think the "native" way maybe good for end user but not a module, actually. It's OK if you reject my PR. I wrote this module hope there is another way to bind or extends the Famo.us modules to do more things on the Web Notification API.

Have a nice day and hope it not disturb you :-)

**Comment by andrewdeandrade** [comment]
@hinablue AFAICT there is nothing in the web notification API that is specific to famous. Do you have something specific in mind regarding how notifications may manifest themselves in famous?

**Comment by michaelobriena** [comment]
@hinablue any suggestions on what you are looking for.

**Pull request closed without merging**
